/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.model.ChiTietSP;
import com.mycompany.model.DongSP;
import com.mycompany.model.MauSac;
import com.mycompany.model.NSX;
import com.mycompany.model.SanPham;
import com.mycompany.service.CTSPInterface;
import com.mycompany.service.DongSPInterface;
import com.mycompany.service.MauSacInterface;
import com.mycompany.service.NSXInterface;
import com.mycompany.service.SanPhamInterface;
import com.mycompany.service.impl.CTSPImpl;
import com.mycompany.service.impl.DongSPImpl;
import com.mycompany.service.impl.MauSacImpl;
import com.mycompany.service.impl.NSXImpl;
import com.mycompany.service.impl.SanPhamImpl;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FormCTSP extends javax.swing.JFrame {

    /**
     * Creates new form FormCTSP
     */
    private CTSPInterface cTSPInterface = new CTSPImpl();
    private SanPhamInterface sanPhamInterface = new SanPhamImpl();
    private MauSacInterface mauSacInterface = new MauSacImpl();
    private NSXInterface nSXInterface = new NSXImpl();
    private DongSPInterface dongSPInterface = new DongSPImpl();

    public FormCTSP() {
        initComponents();
        hienThiCBBSP(sanPhamInterface.getAll());
        hienThiCBBMauSac(mauSacInterface.getAll());
        hienThiCBBDongSP(dongSPInterface.getAll());
        hienThiCBBNNSX(nSXInterface.getAll());
        loadTable(cTSPInterface.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbSP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbNSX = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbDSP = new javax.swing.JComboBox<>();
        cbbMS = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        txtNamBH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblIDCTSP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bảng chi tiết sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Tên NSX");

        jLabel4.setText("Tên DongSP");

        jLabel5.setText("Màu Sắc");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Năm bảo hành");

        jLabel8.setText("Mô tả");

        jLabel9.setText("Giá nhập");

        txtMoTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoTaActionPerformed(evt);
            }
        });

        jLabel10.setText("Giá bán");

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "Tên NSX", "Tên DSP", "Tên Mầu sắc", "Số lượng", "Năm BH", "Mô tả", "Giá nhập", "Giá bán", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTSP);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbbSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbbMS, 0, 125, Short.MAX_VALUE)
                                            .addComponent(cbbNSX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbbDSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnThem)
                                .addGap(80, 80, 80)
                                .addComponent(btnSua)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamBH, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtGiaBan)
                                        .addComponent(txtMoTa)
                                        .addComponent(txtGiaNhap)))
                                .addComponent(btnXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lblIDCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(38, 38, 38))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblIDCTSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiCBBSP(List<SanPham> list) {
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbbSP.getModel();
        for (SanPham sanPham : list) {
            comboBoxModel.addElement(sanPham);
        }
    }

    public void hienThiCBBMauSac(List<MauSac> list) {
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbbMS.getModel();
        for (MauSac mauSac : list) {
            comboBoxModel.addElement(mauSac);
        }
    }

    public void hienThiCBBDongSP(List<DongSP> list) {
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbbDSP.getModel();
        for (DongSP dongSP : list) {
            comboBoxModel.addElement(dongSP);
        }
    }

    public void hienThiCBBNNSX(List<NSX> list) {
        DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) cbbNSX.getModel();
        for (NSX nsx : list) {
            comboBoxModel.addElement(nsx);
        }
    }

    private void setIndexCbbSP(String ten){
        int count = -1;
        List<SanPham> listSP = sanPhamInterface.getAll();
        for (SanPham sanPham : listSP) {
            count ++;
            if(sanPham.getTenSp().equals(ten)){
                System.out.println(count);
                if(count >1) {
                    count = 0;
                }
                cbbSP.setSelectedIndex(count);
            }
        }
    }
    private void setIndexCbbNSX(String ten){
        int count = -1;
        List<NSX> listNSX = nSXInterface.getAll();
        for (NSX nsx : listNSX) {
            count ++;
            if(nsx.getTenNSX().equals(ten)){
                cbbNSX.setSelectedIndex(count);
            }
        }
    }
    private void setIndexCbbDSP(String ten){
        int count = -1;
        List<DongSP> listDSP = dongSPInterface.getAll();
        for (DongSP dongSP : listDSP) {
            count ++;
            if(dongSP.getTenDSP().equals(ten)){
                cbbDSP.setSelectedIndex(count);
            }
        }
    }
    private void setIndexCbbMS(String ten){
        int count = -1;
        List<MauSac> listMS = mauSacInterface.getAll();
        for (MauSac mauSac : listMS) {
            count ++;
            if(mauSac.getTenMauSac().equals(ten)){
                cbbMS.setSelectedIndex(count);
            }
        }
    }
    
    
    public void loadTable(List<ChiTietSP> ctsp) {
        DefaultTableModel dtm = (DefaultTableModel) tblCTSP.getModel();
        dtm.setRowCount(0);
        int i = 1;

        for (ChiTietSP chiTietSP : ctsp) {
            Object[] rowData = {
                i++,
                chiTietSP.getSanPham().getTenSp(),
                chiTietSP.getnSX().getTenNSX(), chiTietSP.getDongSP().getTenDSP(),
                chiTietSP.getMauSac().getTenMauSac(), chiTietSP.getSoLuongTon(),
                chiTietSP.getNamBH(), chiTietSP.getMoTa(), chiTietSP.getGiaNhap(), chiTietSP.getGiaBan(),
                chiTietSP.getId()
            };
            dtm.addRow(rowData);
        }
    }

    public ChiTietSP getData() {
        SanPham maSP = (SanPham) cbbSP.getSelectedItem();
        NSX maNSX = (NSX) cbbNSX.getSelectedItem();
        DongSP maDongSP = (DongSP) cbbDSP.getSelectedItem();
        MauSac maMauSac = (MauSac) cbbMS.getSelectedItem();
        String soluong = txtSoLuong.getText();
        String namBH = txtNamBH.getText();
        String moTa = txtMoTa.getText();
        String giaNhap = txtGiaNhap.getText();
        String giaBan = txtGiaBan.getText();
        ChiTietSP ctsp = new ChiTietSP(Integer.parseInt(namBH), moTa, Integer.parseInt(soluong), Float.parseFloat(giaNhap), Float.parseFloat(giaBan));


        ctsp.setSanPham(maSP);
        ctsp.setDongSP(maDongSP);
        ctsp.setMauSac(maMauSac);
        ctsp.setnSX(maNSX);

        return ctsp;
    }
    private void txtMoTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoTaActionPerformed

    }//GEN-LAST:event_txtMoTaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ChiTietSP chiTietSP = getData();
        if (chiTietSP == null) {
            return;
        }
        if (cTSPInterface.add(chiTietSP)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable(cTSPInterface.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        ChiTietSP chiTietSP = getData();
        String id = lblIDCTSP.getText();
        chiTietSP.setId(id);
        if (cTSPInterface.update(id, chiTietSP)) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTable(cTSPInterface.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked
        int row = tblCTSP.getSelectedRow();
        if (row == -1) {
            return;
        }
        setIndexCbbSP(tblCTSP.getValueAt(row, 1).toString());
        setIndexCbbNSX(tblCTSP.getValueAt(row, 2).toString());
        setIndexCbbDSP(tblCTSP.getValueAt(row, 3).toString());
        setIndexCbbMS(tblCTSP.getValueAt(row, 4).toString());
        txtSoLuong.setText(tblCTSP.getValueAt(row, 5).toString());
        txtNamBH.setText(tblCTSP.getValueAt(row, 6).toString());
        txtMoTa.setText(tblCTSP.getValueAt(row, 7).toString());
        txtGiaNhap.setText(tblCTSP.getValueAt(row, 8).toString());
        txtGiaBan.setText(tblCTSP.getValueAt(row, 9).toString());
        lblIDCTSP.setText(tblCTSP.getValueAt(row, 10).toString());
    }//GEN-LAST:event_tblCTSPMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String id = lblIDCTSP.getText();
        if (cTSPInterface.delete(id)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadTable(cTSPInterface.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCTSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCTSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCTSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCTSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCTSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDSP;
    private javax.swing.JComboBox<String> cbbMS;
    private javax.swing.JComboBox<String> cbbNSX;
    private javax.swing.JComboBox<String> cbbSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIDCTSP;
    private javax.swing.JTable tblCTSP;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNamBH;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
